[build]
command = "npm run build"
publish = "dist"
edge_functions = "edge-functions"

[functions]
directory = "functions"

[functions.mastodon]
schedule = "15,45 * * * *"

[functions.rebuild]
schedule = "0 * * * *"

[[edge_functions]]
function = "scrobble"
path = "/api/scrobble"

[[edge_functions]]
function = "search"
path = "/api/search"

[[edge_functions]]
function = "playing"
path = "/api/playing"

[[redirects]]
from = "/api/artist-import"
to = "/.netlify/functions/artist-import"
status = 200
query = "*"

[[redirects]]
from = "/scripts/util.js"
to = "https://plausible.io/js/plausible.outbound-links.tagged-events.js"
status = 200
force = true

[[redirects]]
from = "/api/event"
to = "https://plausible.io/api/event"
status = 200
force = true
