export const staticSitemapPages = [
  { url: "https://coryd.dev/books" },
  { url: "https://coryd.dev/books/years/2018" },
  { url: "https://coryd.dev/books/years/2019" },
  { url: "https://coryd.dev/books/years/2020" },
  { url: "https://coryd.dev/books/years/2021" },
  { url: "https://coryd.dev/books/years/2022" },
  { url: "https://coryd.dev/books/years/2023" },
  { url: "https://coryd.dev/books/years/2024" },
  { url: "https://coryd.dev/music" },
  { url: "https://coryd.dev/music/this-week/albums" },
  { url: "https://coryd.dev/music/this-week/artists" },
  { url: "https://coryd.dev/music/this-month" },
  { url: "https://coryd.dev/music/this-month/albums" },
  { url: "https://coryd.dev/music/this-month/artists" },
  { url: "https://coryd.dev/watching" },
  { url: "https://coryd.dev/watching/favorites/movies" },
  { url: "https://coryd.dev/watching/favorites/shows" },
  { url: "https://coryd.dev/watching/recent/movies" },
  { url: "https://coryd.dev/watching/recent/shows" },
  { url: "https://coryd.dev/posts" },
  { url: "https://coryd.dev/links" },
];
