name: Scheduled deploy

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  trigger-netlify-build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Netlify Build Hook
        run: |
          curl -X POST -d '{}' \
            -H "Content-Type: application/json" \
            "${{secrets.DEPLOY_HOOK}}"
